source 'https://github.com/southfox/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'


use_frameworks!

target 'JFWindguru_Example' do
  pod 'JFWindguru', :path => '../'
  pod 'JFCore', :path => '../../jfcore'
  pod 'SCLAlertView', '~> 0.7'

  target 'JFWindguru_Tests' do
    inherit! :search_paths

    
  end
end

target 'JFWindguruWatch Extension' do
  platform :watchos, '2.2'
  pod 'JFWindguru', :path => '../'
end


