source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'JFWindguruPure_Example' do
  pod 'JFWindguruPure', :path => '../'
  pod 'SCLAlertView', '~> 0.7'

  target 'JFWindguruPure_Tests' do
    inherit! :search_paths

    
  end
end

target 'JFWindguruPureWatch Extension' do
  platform :watchos, '2.2'
  pod 'JFWindguruPure', :path => '../'
end


target 'JFWindguru_Example' do
  pod 'JFWindguru', :path => '../'
  pod 'SCLAlertView', '~> 0.7'

  target 'JFWindguru_Tests' do
    inherit! :search_paths

    
  end
end

target 'JFWindguruWatch Extension' do
  platform :watchos, '2.2'
  pod 'JFWindguru', :path => '../'
end


